feat(Contexts): enable nav bar display logic
nextcloud/tables pull request #1193
Opened 2024-07-12 11:06 UTC by blizzz

contributes to #1177

It was temporarily disabled and shown by default as we did not have web UI controls to configure it.

* [ ] move some logic into the mapper, [cf. TODO in code](https://github.com/nextcloud/tables/compare/enh/1177/enable-nav-display-logic?expand=1#diff-a4df385ae09b07cf4c026556ce1d2eb17b955736ea7f57e0f925067af9659225R47)

2024-07-23 10:59 UTC, juliushaertl approved these changes
Backend change looks good 👍

2024-08-06 18:47 UTC, juliushaertl requested changes
Let me block the merge just to be sure this doesn't get lost from the initial post

⚠️ merge only with the frontend tasks as laid out in https://github.com/nextcloud/tables/issues/1177#issuecomment-2225363092

2024-08-06 18:54 UTC, juliushaertl commented
Great, thanks :)

2024-09-02 14:09 UTC, blizzz commented
> It seems there's no way for an owner to modify their navigation entry if there are no shares? Creating an application without shares means there's no navigation entry, and no way to change it. @blizzz

This is accurate. We bound the nav bar display state to sharing. Also the share id is part of the primary key.

I do see it is reasonable to have this setting for non-shared applications, but spontaneously a quick solution that is not too terrible does not come to my mind. Is it a blocker?

2024-09-02 14:26 UTC, blizzz commented
> > > It seems there's no way for an owner to modify their navigation entry if there are no shares? Creating an application without shares means there's no navigation entry, and no way to change it. @blizzz
> > 
> > 
> > This is accurate. We bound the nav bar display state to sharing. Also the share id is part of the primary key.
> > I do see it is reasonable to have this setting for non-shared applications, but spontaneously a quick solution that is not too terrible does not come to my mind. Is it a blocker?
> 
> Maybe not a blocker, but still inconvenient and not very user-friendly. The UI right now doesn't look great, and I can't seem to fix it due to this: #1295

Yup, I am with you there. Need to think about a good strategy.

2024-11-19 20:30 UTC, blizzz commented
![Screenshot_20241119_212920](https://github.com/user-attachments/assets/8e2628f8-a48f-429c-afb4-196b19b05552)

@enjeck I feel a bit disconnected. That toggle there, changing it does not have any effect via GUI.

2025-01-09 21:42 UTC, blizzz commented
Remaining one: https://github.com/nextcloud/tables/pull/1250, it should go together with this PR

2025-01-10 12:25 UTC, juliusknorr approved these changes

2025-01-10 12:30 UTC, merged