feat: Add UI elements to modify navigation display
nextcloud/tables pull request #1295
Opened 2024-08-16 19:22 UTC by enjeck

Part of https://github.com/nextcloud/tables/issues/1177 and https://github.com/nextcloud/tables/pull/1193

Todo
- [x] ensure it works when you update a context
- [x] ensure it works for owners and recipients too
- [x] Discuss the UI and copy
- [x] Ensure self-shares to the owner are deleted when share is deleted

2024-08-22 15:14 UTC, jancborchardt requested changes
@enjeck nice!

So unless I misunderstand something, the settings seem can be simplified. As admins are also just users, they can use the navigation preference like everyone else.

The main settings should only say:
> [ ] Show in app list

As a single checkbox, no subheading needed. It can have a color-text-maxcontrast sentence below saying "This can be overridden by a per-account preference."


For the left navigation entry, same wording and setting
> [ ] Show in app list

2024-12-16 20:40 UTC, blizzz commented
One little thing needed: with switching away from the three modes to just two modes, we also have to remove this condition: 

https://github.com/nextcloud/tables/blob/4b7e5a7734558478bbdef447cc16c2a47b41acd6/lib/Db/ContextMapper.php#L189-L190

Otherwise a share owner cannot remove the entry for themselves. Works fine then!

In the backend, we should remove the third option, now that is is unnecessary.

2024-12-16 20:43 UTC, blizzz commented on src/shared/constants.js
> +	NAV_ENTRY_MODE_RECIPIENTS: 1, // nav bar entry for share recipients, but not the owner
since we now only set HIDDEN or ALL, we can remove RECIPIENTS and its usages, right? (same for backend as written in the other comment). :broom:

2024-12-17 19:34 UTC, blizzz commented
Related: https://github.com/nextcloud/server/pull/49904

2025-01-06 15:48 UTC, blizzz commented on lib/Controller/NavigationController.php
> +class NavigationController extends \OC\Core\Controller\NavigationController {
By suppression only so far. I pushed a commit that updates the baseline accordingly. The command I ran is `composer run psalm -- --set-baseline=tests/psalm-baseline.xml`.

2025-01-07 10:38 UTC, juliusknorr commented on src/modules/modals/CreateContext.vue
> +					Show in app list
Should be translatable

2025-01-07 10:38 UTC, juliusknorr commented on src/modules/modals/CreateContext.vue
> +					This can be overridden by a per-account preference
Should be translatable

2025-01-07 10:38 UTC, juliusknorr commented on src/modules/modals/EditContext.vue
> +					Show in app list
Should be translatable

2025-01-07 10:38 UTC, juliusknorr commented on src/modules/modals/EditContext.vue
> +					This can be overridden by a per-account preference
Should be translatable

2025-01-07 10:39 UTC, juliusknorr commented on src/modules/navigation/partials/NavigationContextItem.vue
> +				Show in app list
Should be translatable

2025-01-07 10:39 UTC, juliusknorr reviewed
Small nitpicks, but otherwise looks good 👍

2025-01-09 15:33 UTC, juliusknorr approved these changes
Tested and works. Also reviewed the backend bits of the base PR.

2025-01-09 21:01 UTC, merged